version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: ./_docker/DockerfileNginx
    volumes:
        - ./:/app/
    depends_on:
      - app
    restart: "unless-stopped"
    ports: ["8080:80"]

  app:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: ./_docker/Dockerfile
    volumes:
      - ./:/app/
